name: "Bug report"
description: "Incluye toda la información de tu participación"
title: "[Participación]: <inserta-aqui-tu-nick-o-nombre>"
labels: ["registro"]
body:
  - type: markdown
    attributes:
      value: "## Pre-requisitos"
  - type: checkboxes
    id: pre-requisitos
    attributes:
      label: Señala los requisitos cumplidos
      description: |
        Asegúrate de cumplir estos requisitos antes de registrarte
      options:
        - label: Mi aplicación usa Vercel SDK AI de alguna forma
          required: true
        - label: |
            Mi aplicación está desplegada y funciona
          required: true
  - type: markdown
    attributes:
      value: "## Información"
  - type: input
    id: nombre-equipo
    attributes:
      label: Escribe tu nombre o el del equipo
      placeholder: midudev
  - type: input
    id: nombre-proyecto
    attributes:
      label: Nombre del Proyecto
      placeholder: Mi impresionante proyecto
  - type: textarea
    id: descripcion-proyecto
    attributes:
      label: Descripción del Proyecto
      description: Breve descripción de lo que hace tu proyecto
      placeholder: Mi proyecto te permite recuperar el ALT de las imágenes...
  - type: textarea
    id: informacion-bug
    attributes:
      label: Información del bug
      description: Aporta información sobre el bug
      placeholder: Este bug ocurre cuando ...
  - type: textarea
    id: pasos-reproducir
    attributes:
      label: Pasos para reproducirlo
      description: Pasos necesarios para reproducir el bug
      placeholder: |
        1. Paso1
        2. Paso2
  - type: markdown
    attributes:
      value: "# Contexto"
  - type: dropdown
    id: navegadores
    attributes:
      label: ¿En qué navegadores encuentras el problema?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Opera
        - Todos los navegadores
  - type: input
    id: version-navegador
    attributes:
      label: Versión del navegador
      description: Versión del navegador en el cuál encuentras el problema
      placeholder: Chrome v124.0.6367.92 ...
  - type: dropdown
    id: sistema-operativo
    attributes:
      label: Sistema operativo
      description: Sistema operativo en el cuál encuentras el problema
      multiple: true
      options:
        - Windows
        - MacOS
        - Linux
        - Android
        - Todos los sistemas
  - type: markdown
    attributes:
      value: "# Información adicional"
  - type: textarea
    attributes:
      label: Añade información adicional si fuese necesario
      description: Imágenes, link del código, fragmento de código ...
      placeholder: |
        ```typescript
        const variable = "..."
        ```
        ...